PhysCenter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kshapp.urls', namespace='kshapp')),
    path('accounts/', include('users.urls', namespace='users')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kshapp/urls.py
from django.urls import path 
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'kshapp'

urlpatterns = [
    path('', views.index, name='home'),
    path('sections', views.sections, name='sections'),
    path('new-section', views.new_section, name='new-section'),
    path('section-detail/<int:pk>', views.SectionView.as_view(), name='section-detail'),
    path('edit-section', views.edit_section, name='edit-section'),
    path('patients', views.patients, name='patients'),
    path('patients/patient/<int:pk>', views.view_patient, name='view-patient'),
    path('new-patient', views.new_patient, name='new-patient'),
    path('delete-patient', views.delete_patient, name='delete-patient'),
    path('edit-patient', views.edit_patient, name='edit-patient'),
    path('new-patient-type', views.new_patient_type, name='new-patient-type'),
    path('disability', views.new_disability, name='new-disability'),
    path('new-appointment', views.new_appointment, name='new-appointment'),
    path('appointments', views.appointments, name='appointments'),
    path('appointment/<int:pk>', views.appointment_detail, name='appointment-detail'),
    path('edit-appoint', views.edit_appoint, name='edit-appoint'),
    path('therapists', views.therapists, name='therapists'),
    path('therapist-detail/<int:pk>', views.TherapistView.as_view(), name='therapist-detail'),
    path('edit-therapist', views.edit_therapist, name='edit-therapist'),
    path('new-therapist', views.new_therapist, name='new-therapist'),
    path('therapist-appointments', views.therapist_appointments, name='therapist-appointments'),
    path('edit-therapist-appointment', views.edit_therapist_appointment, name='edit-therapist-appointment'),
    path('therapist-all-appointments', views.therapist_all_appointments, name='therapist-all-appointments'),
    path('reports', views.reports, name='reports'),
    path('patient_reports', views.patient_reports, name='patient_reports'),
    path('note', views.note, name='note'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from .views import UserView, signup, login_view

from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    # path('login', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('login', login_view, name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='/accounts/login'), name='logout'),
    path('profile/', login_required(UserView.as_view()), name='profile'),
    # path('signup', signup, name='signup')

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kshapp/models.py
from django.db import models
from django.utils import timezone
from django.utils.timezone import datetime
from django.contrib.auth import get_user_model
User = get_user_model()


class Disability(models.Model):

    dis_type = models.CharField(max_length=200, null=False, blank=False)
    note = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return self.dis_type


class PatientType(models.Model):

    patient_type = models.CharField(max_length=200, null=False, blank=False)
    branch = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return self.patient_type


class Patient(models.Model):

    GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    NATION = (
        ('Kuwaiti', 'Kuwaiti'),
        ('Egyption', 'Egyption'),
        ('Iraqi', 'Iraqi'),
        ('Jordanian', 'Jordanian'),
        ('Non-Kuwaiti', 'Non-Kuwaiti'),
        ('Saudi', 'Saudi'),
        ('Syrian', 'Syrian'),
        ('Yemeni', 'Yemeni'),
        ('Indian', 'Indian'),
        ('Bangladesh', 'Bangladesh'),
        ('Eritrean', 'Eritrean'),
        ('Lebanese', 'Lebanese'),
        ('Irani', 'Irani'),
        ('Somali', 'Somali'),
        ('Other', 'Other'),
        


    )
    created = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=250, null=False, blank=False)
    patient_type = models.ForeignKey(PatientType, on_delete=models.CASCADE, null=False, blank=False)
    civil_Id = models.CharField(max_length=200, null=False, blank=False,unique=True)
    type_disability = models.ForeignKey(Disability, on_delete=models.CASCADE, null=False, blank=False) 
    Date_Of_Birth = models.DateField(null=False, blank=False)
    email = models.CharField(max_length=200, null=False, blank=False)
    adress = models.TextField(null=False, blank=False)
    phone = models.CharField(max_length=50, null=False, blank=False)
    photo = models.ImageField(upload_to='images/patients', null=True, blank=True)
    ID_photo = models.ImageField(upload_to='images/patients', null=True, blank=True)
    uplode = models.FileField(upload_to='images/patients', null=True, blank=True)
    gender = models.CharField(max_length=200, null=True, blank=True, choices=GENDER)
    nationality = models.CharField(max_length=200, null=False, blank=False,choices=NATION)
    parents_contact = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return self.name


class Section(models.Model):

    section_service = models.CharField(max_length=200, null=False, blank=False)
    main_section = models.ForeignKey('self',on_delete=models.CASCADE, null=True, blank=True)
    note = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return self.section_service


class Therapist(User):
    phone = models.CharField(max_length=200, null=False, blank=False)
    adress = models.CharField(max_length=200, null=False, blank=False)
    sections = models.ForeignKey(Section, on_delete=models.CASCADE, null=False, blank=False)
    avtar = models.ImageField(upload_to='images/therapist', blank=True)
    
    def __str__(self):
        return self.name


class Appointment(models.Model):

    Action = (
        ('Pending', 'Pending'),
        ('Done', 'Done'),

    )    

    STATUS = (
        ('Attend', 'Attend'),
        ('Absent', 'Absent'),
        ('Compensate', 'Compensate'),
        ('Discharged', 'Discharged'),

    )

    Time = (
        ("8:00", "8:00"),
        ("8:45", "8:45"),
        ("9:30", "9:30"),
        ("10:15", "10:15"),
        ("11:00", "11:00"),
        ("11:45", "11:45"),
        ("12:30", "12:30"),
        ("01:15", "01:15"),
        ("2:00", "2:00"),
        ("2:45", "2:45"),
        ("3:30", "3:30"),
        ("4:15", "4:15"),
        ("5:00", "5:00"),
        ("5:45", "5:45"),
        ("6:30", "6:30"),
        ("7:15", "7:15"),
        ("8:00", "8:00"),
        ("8:45", "8:45"),
        ("9:30", "9:30"),
        ("10:15", "10:15"),

    )

    created = models.DateTimeField(default=timezone.now)
    date = models.DateField(null=True, blank=True) 
    time = models.CharField(max_length=200, null=True, blank=True, choices=Time)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=False, blank=False)
    service = models.ForeignKey (Section, on_delete=models.CASCADE, null=True, blank=True)
    note = models.CharField(max_length=200, null=True, blank=True)
    status = models.CharField(max_length=200, null=True, blank=True, choices=STATUS)
    action = models.CharField(max_length=200, null=True, blank=True, choices=Action,default='Pending')
    therapist = models.ForeignKey(Therapist, on_delete=models.CASCADE, null=False, blank=False, related_name='appointments')

    class Meta:
        unique_together = ('date', 'time', 'therapist')

    def __str__(self):
        return str(self.patient)

templates/pages/appointments.html
{% extends 'base.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="main-content container-fluid px-4">
            <h1 class="mt-4">Welcome
                {% if request.user.name %}{{request.user.name}}{% else %}{{request.user}}{%endif%}
            </h1>
            <div class="row">
                <div class="col-xl-3 col-md-6">
                    <div class="card text-center bg-primary text-white mb-4">
                      
                    </div>
                </div>
            </div> 
        
            <h1>Appointments</h1>
            <div class="d-flex flex-row-reverse m-2 p-2">
                <button type="button" id="add_appointment_btn" class="btn btn-success m-1" data-togle="modal"
                    data-target="#addAppointment">Add Appointment</button>
            </div>
            <br>
            <h2>    </h2>
            <form class="row" action="{% url 'kshapp:appointments' %}" method="GET">
                <input type="text" name="q" value="{{request.GET.q}}" class="col-4" style="width: 40%;" data-table="order-table" placeholder="Appointments Search .." />
                <button type="submit" class="btn btn-outline-info m-1 col-1" >search</button>
            </form>
            <table class="order-table table" class="table table-striped" >
                <thead>
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Time</th>
                        <th scope="col">Patient</th>
                        <th scope="col">Note</th>
                        <th scope="col">Therapist</th>
                        <th scope="col">Status</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for appointment in appointments %}
                    <tr>
                        <!-- TODO: redirect user to appointment page -->
                        <th scope="row"><a type="button" href="{% url 'kshapp:appointment-detail' appointment.id%}" class="text-info text-decoration-none">{{appointment.date}}</a></th>
                        <td>{{appointment.time}}</td>
                        <td>{{appointment.patient}}</td>
                        <td>{{appointment.note}}</td>
                        <td>{{appointment.therapist}}</td>
                        <td>{{appointment.status}}</td>
                        <td class="text-center">
                            <form id="csrf_appointment_form" class="d-none">
                                {% csrf_token %}
                            </form>
                            <button type="button" data-appointID="{{appointment.id}}"  class="btn btn-outline-success mx-2 col edit_appointment_btn"><i class="fas fa-edit"></i> Edit</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if appointments.has_other_pages %}
            <nav aria-label="Page navigation example ">
                <ul class="pagination">
                    {% if appointments.has_previous %}
                    <li class="page-item">
                    <a class="page-link" href="?page={{ appointments.previous_page_number }}"" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                    </li>
                    {% endif %}
                    {% for i in appointments.paginator.page_range %}
                        {% if appointments.number == i %}
                            <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if appointments.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ appointments.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                            </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}

            <div class="modal fade" id="addAppointment" >
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header border-bottom-0">
                            <h5 class="modal-title">Create Appointment</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form method="POST" action="{% url 'kshapp:new-appointment' %}"  enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="modal-body">
                            {{ appoint_form.as_p }}
                            </div>
                            <div class="modal-footer border-top-0 d-flex justify-content-center">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="modal fade" id="modalEditAppoint" >
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header border-bottom-0">
                            <h5 class="modal-title">Edit Appointment</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form id="editAppointForm" method="POST" action="{% url 'kshapp:edit-appoint' %}"  enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="hidden" id="appointID" name="appointID" value="">
                            <div id='edit_appoint_body' class="modal-body">

                            </div>
                            <div class="modal-footer border-top-0 d-flex justify-content-center">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </main>
</div>
{% endblock %}

{% block afterload %}
<script>
$('#add_appointment_btn').click(function(){
    $('#addAppointment').modal('show');
    $('#id_date').attr('type', 'date');
    $('input').each(function(){
        $(this).addClass('form-control')
    })
    $('select').each(function(){
        $(this).addClass('form-control')
    })
})

function editAppointment(patientID){
    token = $("#csrf_appointment_form").find('input[name=csrfmiddlewaretoken]').val()
    $.get({
        'url': '{% url "kshapp:edit-appoint" %}',
        'data': {
            'csrfmiddlewaretoken': token,
            'appointID': appointID
        },
        'success': function (response) {
            $('#edit_appoint_body p').remove()
            response = JSON.parse(response);
            if (response.status == '1') {
                $('#modalEditAppoint').modal('show');
                $.when($('#edit_appoint_body').append(JSON.parse(response.data))).then(
                    $('#modalEditAppoint input').each(function(){
                        $(this).addClass('form-control')
                    }),
                    $('#modalEditAppoint select').each(function(){
                        $(this).addClass('form-control')
                    }),
                    $('#modalEditAppoint textarea').each(function(){
                        $(this).addClass('form-control')
                    }),
                    $('#modalEditAppoint #id_date').attr('type', 'date'),
                    $('#editAppointForm input[name="appointID"]').val(appointID)
                )

            } else {
                alertPopup('Fialed', 'Failed to get appointment detail', 'danger')
            }
        },
        'error': function () {
            alert("Server Error");
        }
    })
}

$('.edit_appointment_btn').on('click', function(){
    appointID = $(this).attr('data-appointID')
    editAppointment(appointID)
})

</script>

<script>
    (function() {
        'use strict';
    
    var TableFilter = (function() {
     var Arr = Array.prototype;
            var input;
      
            function onInputEvent(e) {
                input = e.target;
                var table1 = document.getElementsByClassName(input.getAttribute('data-table'));
                Arr.forEach.call(table1, function(table) {
                    Arr.forEach.call(table.tBodies, function(tbody) {
                        Arr.forEach.call(tbody.rows, filter);
                    });
                });
            }
    
            function filter(row) {
                var text = row.textContent.toLowerCase();
           //console.log(text);
          var val = input.value.toLowerCase();
          //console.log(val);
                row.style.display = text.indexOf(val) === -1 ? 'none' : 'table-row';
            }
    
            return {
                init: function() {
                    var inputs = document.getElementsByClassName('table-filter');
                    Arr.forEach.call(inputs, function(input) {
                        input.oninput = onInputEvent;
                    });
                }
            };
     
        })();
    
      /*console.log(document.readyState);
        document.addEventListener('readystatechange', function() {
            if (document.readyState === 'complete') {
          console.log(document.readyState);
                TableFilter.init();
            }
        }); */
      
     TableFilter.init(); 
    })();
</script>
{% endblock afterload %}

templates/pages/new.html

{% extends 'base.html' %}

{% block content %}

<div id="layoutSidenav_content">
  <main>
      <div class="main-content container-fluid px-4">
          <h1 class="mt-4">New subscribe</h1>
          <ol class="breadcrumb mb-4">
              <li class="breadcrumb-item active">New</li>
          </ol>
          <div class="innercontent">
              
            <form class="row g-3" method="POST">
                 {% csrf_token %}
           
                     {{form.name}} 
              
              <div class="col-12">
                  <button type="submit" class="btn btn-primary">Save</button>
                </div>  
          </form>
              </div>
          </div>
        
          </div>
       
      </div>
  </main>

</div>

{% endblock %}


templates/pages/sections.html
{% extends 'base.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="main-content container-fluid px-4">
            <h1 class="mt-4">Welcome
                {% if request.user.name %}{{request.user.name}}{% else %}{{request.user}}{%endif%}
            </h1>
            <div class="row">
                <div class="col-xl-3 col-md-6">
                    <div class="card text-center bg-primary text-white mb-4">
                      
                    </div>
                </div>
            </div> 
        
            <h1>Sections</h1>
            <div class="d-flex flex-row-reverse m-2 p-2">
                <button type="button" id="add_sec_btn" class="btn btn-success m-1" data-togle="modal"
                    data-target="#addSection">New Section</button>
            </div>

            <table class="table table-striped" >
                <thead>
                    <tr>
                        <th scope="col">Section service</th>
                        <th scope="col">Main Section</th>
                        <th scope="col">Note</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for sec in sections %}
                    <tr>
                        <!-- TODO: redirect user to appointment page -->
                        <th scope="row"><a type="button" href="{% url 'kshapp:section-detail' sec.id%}" class="text-info text-decoration-none">{{sec.section_service}}</a></th>
                        <td>{{sec.main_section}}</td>
                        <td>{{sec.note}}</td>
                        <td class="text-center">
                            <form id="csrf_sec_form" class="d-none">
                                {% csrf_token %}
                            </form>
                            <button type="button" data-secID="{{sec.id}}"  class="btn btn-outline-success mx-2 col edit_sec_btn"><i class="fas fa-edit"></i> Edit</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="modal fade" id="addSection" >
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header border-bottom-0">
                            <h5 class="modal-title">Create Section</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form method="POST" action="{% url 'kshapp:new-section' %}"  enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="modal-body">
                            {{ sec_form.as_p }}
                            </div>
                            <div class="modal-footer border-top-0 d-flex justify-content-center">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="modal fade" id="modalEditSec" >
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header border-bottom-0">
                            <h5 class="modal-title">Edit Section</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form id="editSectionForm" method="POST" action="{% url 'kshapp:edit-section' %}"  enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="hidden" id="secID" name="secID" value="">
                            <div id='edit_sec_body' class="modal-body">

                            </div>
                            <div class="modal-footer border-top-0 d-flex justify-content-center">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </main>
</div>
{% endblock %}

{% block afterload %}
<script>
$('#add_sec_btn').click(function(){
    $('#addSection').modal('show');
    $('#id_date').attr('type', 'date');
    $('input').each(function(){
        $(this).addClass('form-control')
    })
    $('select').each(function(){
        $(this).addClass('form-control')
    })
})

function editSection(patientID){
    token = $("#csrf_appointment_form").find('input[name=csrfmiddlewaretoken]').val()
    $.get({
        'url': '{% url "kshapp:edit-section" %}',
        'data': {
            'csrfmiddlewaretoken': token,
            'secID': secID
        },
        'success': function (response) {
            $('#edit_sec_body p').remove()
            response = JSON.parse(response);
            if (response.status == '1') {
                $('#modalEditSec').modal('show');
                $.when($('#edit_sec_body').append(JSON.parse(response.data))).then(
                    $('#modalEditSec input').each(function(){
                        $(this).addClass('form-control')
                    }),
                    $('#modalEditSec select').each(function(){
                        $(this).addClass('form-control')
                    }),

                    $('#editSectionForm input[name="secID"]').val(secID)
                )

            } else {
                alertPopup('Fialed', 'Failed to get appointment detail', 'danger')
            }
        },
        'error': function () {
            alert("Server Error");
        }
    })
}

$('.edit_sec_btn').on('click', function(){
    secID = $(this).attr('data-secID')
    editSection(secID)
})

</script>
{% endblock afterload %}

templates/pages/therapist-home.html
{% extends 'base.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="main-content container-fluid px-4">
            <h1 class="mt-4">Welcome
                {% if request.user.name %}{{request.user.name}}{% else %}{{request.user}}{%endif%}
            </h1>
            <div class="row">
                <div class="col-xl-3 col-md-6">
                    <div class="card text-center bg-primary text-white mb-4">
                      
                    </div>
                </div>
            </div> 

            <h1>Therapist</h1>
            <!-- <div class="d-flex flex-row-reverse m-2 p-2">
                <button type="button" id="add_sec_btn" class="btn btn-success m-1" data-togle="modal"
                    data-target="#addSection">New Section</button>
            </div> -->

            <table class="table table-striped" >
                <thead>
                    <tr>
                        <th scope="col">Section service</th>
                        <th scope="col">Patient</th>
                        <th scope="col">Time</th>
                        <th scope="col">Date</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for app in appointments %}
                    <tr>
                        <!-- TODO: redirect user to appointment page -->
                        <th scope="row"><a type="button" href="{% url 'kshapp:appointment-detail' app.id%}" class="text-info text-decoration-none">{{app.id}}</a></th>
                        <td>{{app.patient}}</td>
                        <td>{{app.time}}</td>
                        <td>{{app.date}}</td>
                        <td>{{app.status}}</td>
                        <td>{{app.action}}</td>
                        <td class="text-center">
                            <form id="csrf_app_form" class="d-none">
                                {% csrf_token %}
                            </form>
                            <button type="button" data-appID="{{app.id}}" onclick="therapistEditAppoint({{app.id}})"  class="btn btn-outline-success mx-2 col edit_app_btn"><i class="fas fa-edit"></i> Action</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
        <div class="modal fade" id="modalEditTherapistAppoint" >
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header border-bottom-0">
                        <h5 class="modal-title">Edit Appointment</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="editTherapistAppointForm" method="POST" action="{% url 'kshapp:edit-therapist-appointment' %}"  enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" id="appointID" name="appID" value="">
                        <div id='edit_app_body' class="modal-body">

                        </div>
                        <div class="modal-footer border-top-0 d-flex justify-content-center">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}
{% block afterload %}

<script>
    function therapistEditAppoint(appID){
        token = $("#csrf_app_form").find('input[name=csrfmiddlewaretoken]').val()
        $.get({
            'url': '{% url "kshapp:edit-therapist-appointment" %}',
            'data': {
                'csrfmiddlewaretoken': token,
                'appID': appID
            },
            'success': function (response) {
                $('#edit_app_body p').remove()
                response = JSON.parse(response);
                if (response.status == '1') {
                    console.log(JSON.parse(response.data))
                    $('#modalEditTherapistAppoint').modal('show');
                    $.when($('#edit_app_body').append(JSON.parse(response.data))).then(
                        $('#modalEditTherapistAppoint p').each(function(){
                            $(this).addClass('d-none')
                        }),
                        $('#modalEditTherapistAppoint p #id_note').parent().removeClass('d-none'),
                        $('#modalEditTherapistAppoint p #id_status').parent().removeClass('d-none'),
                           
                        $('#modalEditTherapistAppoint input').each(function(){
                            $(this).addClass('form-control')
                        }),
                        $('#modalEditTherapistAppoint select').each(function(){
                            $(this).addClass('form-control')
                        }),
    
                        $('#editTherapistAppointForm input[name="appID"]').val(appID)
                    )
    
                } else {
                    alertPopup('Fialed', 'Failed to get appointment detail', 'danger')
                }
            },
            'error': function () {
                alert("Server Error");
            }

        });
    }
</script>
{% endblock afterload %}