PhysCenter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kshapp.urls', namespace='kshapp')),
    path('accounts/', include('users.urls', namespace='users')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kshapp/urls.py
from django.urls import path 
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'kshapp'

urlpatterns = [
    path('', views.index, name='home'),
    path('sections', views.sections, name='sections'),
    path('new-section', views.new_section, name='new-section'),
    path('section-detail/<int:pk>', views.SectionView.as_view(), name='section-detail'),
    path('edit-section', views.edit_section, name='edit-section'),
    path('patients', views.patients, name='patients'),
    path('patients/patient/<int:pk>', views.view_patient, name='view-patient'),
    path('new-patient', views.new_patient, name='new-patient'),
    path('delete-patient', views.delete_patient, name='delete-patient'),
    path('edit-patient', views.edit_patient, name='edit-patient'),
    path('new-patient-type', views.new_patient_type, name='new-patient-type'),
    path('disability', views.new_disability, name='new-disability'),
    path('new-appointment', views.new_appointment, name='new-appointment'),
    path('appointments', views.appointments, name='appointments'),
    path('appointment/<int:pk>', views.appointment_detail, name='appointment-detail'),
    path('edit-appoint', views.edit_appoint, name='edit-appoint'),
    path('therapists', views.therapists, name='therapists'),
    path('therapist-detail/<int:pk>', views.TherapistView.as_view(), name='therapist-detail'),
    path('edit-therapist', views.edit_therapist, name='edit-therapist'),
    path('new-therapist', views.new_therapist, name='new-therapist'),
    path('therapist-appointments', views.therapist_appointments, name='therapist-appointments'),
    path('edit-therapist-appointment', views.edit_therapist_appointment, name='edit-therapist-appointment'),
    path('therapist-all-appointments', views.therapist_all_appointments, name='therapist-all-appointments'),
    path('reports', views.reports, name='reports'),
    path('patient_reports', views.patient_reports, name='patient_reports'),
    path('note', views.note, name='note'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from .views import UserView, signup, login_view

from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    # path('login', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('login', login_view, name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='/accounts/login'), name='logout'),
    path('profile/', login_required(UserView.as_view()), name='profile'),
    # path('signup', signup, name='signup')

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/parts/footer.html
{% load static %}
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; Kuwait Society for the Hondicapped 2022</div>
            <div>
                <a href="#">Created by Eng : Ahmed Gad -96645146</a>
            </div>
        </div>
    </div>
</footer>

templates/parts/nav.html
{% load static %}

<nav class="sb-topnav navbar navbar-expand c-top-nav">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="{% if request.session.group == 'therapist' %}  {% url 'kshapp:therapist-appointments' %} {% else %} {%url 'kshapp:home'%} {% endif %}">
        <img class="logo" src="{% static 'images/logo.jpg' %}" />
    </a>
    <!-- Sidebar Toggle -->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
         
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
            </ul>
        </li>
        <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
    </ul>
</nav>

templates/parts/sidebar.html
{% load static %}

<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav ">
                    {% if request.session.group == 'therapist' %}
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'kshapp:therapist-appointments'%}">
                                <i class="fa fa-calendar"></i> &nbsp; Today Appointments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " aria-current="page" href="{% url 'kshapp:therapist-all-appointments'%}"> 
                                <i class="fa-solid fa-users"></i> &nbsp; All appointments</a>
                        </li>
                    </ul>
                    {% else %}
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'kshapp:home'%}"> <i
                                    class="fa-solid fa-gauge"></i> &nbsp; Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'kshapp:patients'%}"><i
                                    class="fa-solid fa-graduation-cap"></i> &nbsp; Patients</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'kshapp:sections'%}"> <i
                                    class="fa-solid fa-puzzle-piece"></i> &nbsp; Sections</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'kshapp:appointments'%}"><i class="ml-2 fas fa-table"> </i>
                                &nbsp; Appointments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'kshapp:therapists'%}"><i
                                    class="fa-solid fa-person-chalkboard"></i> &nbsp; Therapists</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'kshapp:reports'%}"><i class="ml-2 fab fa-elementor"> </i>
                                
                                &nbsp; Reports</a>
                        </li>
                    </ul>
                    {% endif %}

                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logged in as:</div>
                {{request.user}}
            </div>
        </nav>
    </div>